import * as Key from '../Key/Key.ts'
import * as KeyCode from '../KeyCode/KeyCode.ts'

const keyCodeMap = {
  [Key.Backquote]: KeyCode.Backquote,
  [Key.Backslash]: KeyCode.Backslash,
  [Key.Backspace]: KeyCode.Backspace,
  [Key.BracketLeft]: KeyCode.BracketLeft,
  [Key.BracketRight]: KeyCode.BracketRight,
  [Key.Comma]: KeyCode.Comma,
  [Key.Delete]: KeyCode.Delete,
  [Key.Digit0]: KeyCode.Digit0,
  [Key.Digit1]: KeyCode.Digit1,
  [Key.Digit2]: KeyCode.Digit2,
  [Key.Digit3]: KeyCode.Digit3,
  [Key.Digit4]: KeyCode.Digit4,
  [Key.Digit5]: KeyCode.Digit5,
  [Key.Digit6]: KeyCode.Digit6,
  [Key.Digit7]: KeyCode.Digit7,
  [Key.Digit8]: KeyCode.Digit8,
  [Key.Digit9]: KeyCode.Digit9,
  [Key.DownArrow]: KeyCode.DownArrow,
  [Key.End]: KeyCode.End,
  [Key.Enter]: KeyCode.Enter,
  [Key.Equal]: KeyCode.Equal,
  [Key.Escape]: KeyCode.Escape,
  [Key.F1]: KeyCode.F1,
  [Key.F10]: KeyCode.F10,
  [Key.F11]: KeyCode.F11,
  [Key.F12]: KeyCode.F12,
  [Key.F13]: KeyCode.F13,
  [Key.F14]: KeyCode.F14,
  [Key.F15]: KeyCode.F15,
  [Key.F16]: KeyCode.F16,
  [Key.F17]: KeyCode.F17,
  [Key.F18]: KeyCode.F18,
  [Key.F19]: KeyCode.F19,
  [Key.F2]: KeyCode.F2,
  [Key.F20]: KeyCode.F20,
  [Key.F21]: KeyCode.F21,
  [Key.F22]: KeyCode.F22,
  [Key.F23]: KeyCode.F23,
  [Key.F24]: KeyCode.F24,
  [Key.F3]: KeyCode.F3,
  [Key.F4]: KeyCode.F4,
  [Key.F5]: KeyCode.F5,
  [Key.F6]: KeyCode.F6,
  [Key.F7]: KeyCode.F7,
  [Key.F8]: KeyCode.F8,
  [Key.F9]: KeyCode.F9,
  [Key.Home]: KeyCode.Home,
  [Key.Insert]: KeyCode.Insert,
  [Key.KeyA]: KeyCode.KeyA,
  [Key.KeyB]: KeyCode.KeyB,
  [Key.KeyC]: KeyCode.KeyC,
  [Key.KeyD]: KeyCode.KeyD,
  [Key.KeyE]: KeyCode.KeyE,
  [Key.KeyF]: KeyCode.KeyF,
  [Key.KeyG]: KeyCode.KeyG,
  [Key.KeyH]: KeyCode.KeyH,
  [Key.KeyI]: KeyCode.KeyI,
  [Key.KeyJ]: KeyCode.KeyJ,
  [Key.KeyK]: KeyCode.KeyK,
  [Key.KeyL]: KeyCode.KeyL,
  [Key.KeyM]: KeyCode.KeyM,
  [Key.KeyN]: KeyCode.KeyN,
  [Key.KeyO]: KeyCode.KeyO,
  [Key.KeyP]: KeyCode.KeyP,
  [Key.KeyQ]: KeyCode.KeyQ,
  [Key.KeyR]: KeyCode.KeyR,
  [Key.KeyS]: KeyCode.KeyS,
  [Key.KeyT]: KeyCode.KeyT,
  [Key.KeyU]: KeyCode.KeyU,
  [Key.KeyV]: KeyCode.KeyV,
  [Key.KeyW]: KeyCode.KeyW,
  [Key.KeyX]: KeyCode.KeyX,
  [Key.KeyY]: KeyCode.KeyY,
  [Key.KeyZ]: KeyCode.KeyZ,
  [Key.LeftArrow]: KeyCode.LeftArrow,
  [Key.Minus]: KeyCode.Minus,
  [Key.PageDown]: KeyCode.PageDown,
  [Key.PageUp]: KeyCode.PageUp,
  [Key.Period]: KeyCode.Period,
  [Key.Plus]: KeyCode.Plus,
  [Key.Quote]: KeyCode.Quote,
  [Key.RightArrow]: KeyCode.RightArrow,
  [Key.SemiColon]: KeyCode.SemiColon,
  [Key.Slash]: KeyCode.Slash,
  [Key.Space]: KeyCode.Space,
  [Key.Star]: KeyCode.Star,
  [Key.Tab]: KeyCode.Tab,
  [Key.UpArrow]: KeyCode.UpArrow,
} as const

export const getKeyCode = (key) => {
  return keyCodeMap[key] ?? KeyCode.Unknown
}
